build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod docker APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}da7027760cd5e1b6d7ee4025ec4396d362981d2ced0617fc5b1bf6466f04210253c12cba46e6eacbf22833b1e6bf3719"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
